[workspace]
resolver = "3"
members = [
    "generate",
    "plugins/plugin_adb",
    "plugins/plugin_desktop",
    "app",
    "server/plugin_manager",
    "server/plugin_d",
    "server/window",
    "server/key",
]
