use rs2ty::{AsTyExt, RecognizedResult, Recognizer, tsty::TsType};
use std::fs::File;
use std::io::Write;

const AUTO_GENERATE: &str = r#"// this file is auto generated by rs2ty, please do not modify it manually.

declare global {
  interface Window {
    bridge: {
      send<T>(command: string, payload: any | undefined): Promise<T>;
    };
  }
}

"#;

fn main() {
    println!("cargo:rerun-if-changed=src/cmd.rs");
    run("bridge", "./src/cmd.rs", "./src/types/bridge.ts").unwrap();
    #[cfg(any(not(debug_assertions), feature = "use-embed"))]
    build_frontend().unwrap();
}

#[cfg(any(not(debug_assertions), feature = "use-embed"))]
fn build_frontend() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:warning=Building frontend assets...");

    let status = std::process::Command::new("cmd")
        .args(["/c", "pnpm", "build"])
        .current_dir("./") // 当前目录是 app crate 根目录
        .status()?;
    if !status.success() {
        return Err("frontend build failed".into());
    }
    Ok(())
}

fn run(name: &str, from: &str, to: &str) -> Result<(), Box<dyn std::error::Error>> {
    let mut recognizer = Recognizer::new(&[name])?;
    recognizer.add_all([from])?;
    let result = &recognizer.recognize()?;
    let mut result: RecognizedResult<TsType> = result.asty();

    let mut file = File::create(to)?;

    writeln!(&mut file, "{AUTO_GENERATE}")?;
    writeln!(&mut file, "type Value = any;")?;

    // 输出所有接口/类型定义
    for (k, v) in result.tys {
        match &v {
            TsType::Object(e) => {
                if !e.is_empty() {
                    writeln!(&mut file, "export interface {k} {v};")?;
                } else {
                    writeln!(&mut file, "type {k} = any;")?;
                }
            }
            TsType::Enum(e) => {
                if !e.is_empty() {
                    writeln!(&mut file, "export type {k} = {v};")?;
                } else {
                    writeln!(&mut file, "type {k} = any;")?;
                }
            }
            _ => {}
        }
    }

    // 生成 command 对象，收集每个方法
    writeln!(&mut file, "\nexport const Command = {{")?;

    for fninfo in result.fns.iter_mut() {
        // 过滤掉 WindowState 参数（同原逻辑）
        let args = &fninfo.args;
        let new_args = args
            .iter()
            .filter(|(_, t)| match t {
                TsType::Name(name) => name != "WindowState",
                _ => true,
            })
            .cloned()
            .collect::<Vec<_>>();
        fninfo.args = new_args;

        // 生成方法体：直接调用 window.bridge.send
        let method_body = if fninfo.args.is_empty() {
            format!(
                "window.bridge.send<{}>('{}', undefined)",
                fninfo.ret, fninfo.name,
            )
        } else {
            format!(
                "window.bridge.send<{}>('{}', {{ {} }})",
                fninfo.ret,
                fninfo.name,
                fninfo
                    .args
                    .iter()
                    .map(|(name, _)| name.to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        };

        // 生成参数列表字符串
        let params_str = fninfo
            .args
            .iter()
            .map(|(name, ty)| format!("{name}: {ty}"))
            .collect::<Vec<_>>()
            .join(", ");

        writeln!(
            &mut file,
            "  {}: ({}) => {},",
            fninfo.name, params_str, method_body
        )?;
    }

    writeln!(&mut file, "}};")?;

    Ok(())
}
